version: "3.1"
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_password
      MYSQL_USER: development
      MYSQL_PASSWORD: development
      MYSQL_DATABASE: task-mate
    ports:
      - 127.0.0.1:3306:3306
